apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpro-mc
  labels:
    app: vpro-mc
spec:
  selector:
    matchLabels:
      app: vpro-mc
  replicas: 1    
  template:
    metadata:
      labels:
        app: vpro-mc
    spec:
      containers:
        - name: vpro-mc
          image: memcached
          ports:
            - containerPort: 11211    

    