apiVersion: v1 
kind: Deployment
metadata:
  name: vpro-rmq
spec:
  selector:
    matchLabels:
      app: vpro-rmq
  replicas: 1    
  template:
    metadata:
      labels:
        app: vpro-rmq
    spec:
      containers:
        - name: vpro-rmq
          image: rabbitmq
          ports:
            - containerPort: 15672
          env:
           - name: RABBITMQ_DEFAULT-PASS
             valueFrom:
              secretKeyRef:
                name: secret-app-k8s
                key: rmq-pass
           - name: RABBITMQ_DEFAULT-USER
             value: "guest"
              


      
  